name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.12.0

# --- DEPENDÊNCIAS DO SEU APP (Todas reunidas aqui) ---
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  webview_flutter: ^4.14.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.1.10
  webview_flutter_web: ^0.2.3+4
  
  # Adicionados para o funcionamento dos alertas/notificações:
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# --- CONFIGURAÇÕES DO FLUTTER ---
flutter:
  uses-material-design: true

  assets:
    - web/icons/gemini-svg.svg
    # Se o seu ícone de celular estiver dentro de assets/icon/, 
    # certifique-se de que a pasta está declarada aqui se for usá-la no app:
    # - assets/icon/

# --- CONFIGURAÇÃO DO GERADOR DE ÍCONES ---
flutter_launcher_icons:
  image_path: "assets/icon/icone.regenerar.png" # Certifique-se de que a imagem está exatamente nesta pasta com este nome!
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    image_path: "web/icons/gemini-svg.svg"
    background_color: "#ffffff"